version: "3.7"
services:
  nginx:
    build: docker/nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    expose:
      - 8080
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/
    networks:
      - weather_app
  php:
    build: docker/php
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: php-fpm
    depends_on:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - weather_app
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - weather_app
  cache:
    image: memcached:1.6-alpine
    networks:
      - weather_app
networks:
  weather_app:
    driver: bridge
